### ISSUE TITLE
Missing 'soundfile' in README 

### ISSUE THREAD

**Issue by davidjohnbaker1** [drensin/Remixatron#3] opened 2018-06-25 10:47 UTC
I cloned a copy of Remixatron to try out infinite jukebox and when I first tried to run it (having never really done any python) and got an error that I was missing the soundfile module. 

Then after running it again I got a few of errors (screen shot below).

<img width="843" alt="screen shot 2018-06-25 at 11 41 18 am" src="https://user-images.githubusercontent.com/10405851/41846060-6ca6e0c8-786d-11e8-9295-3477da2854cc.png">

Any guess as to those errors?

**Comment by drensin** [comment] 2018-06-26 06:17
take a look at this and see if it helps:

https://stackoverflow.com/questions/45708735/no-module-named-soundfile

**Comment by davidjohnbaker1** [comment] 2018-06-27 11:21
Still getting some errors... Sorry if these are rookie questions. 

I tried what some of the comments suggested, but am still getting errors (pictured below) 

<img width="848" alt="screen shot 2018-06-27 at 11 43 54 am" src="https://user-images.githubusercontent.com/10405851/41970944-8fab0e3a-7a04-11e8-868c-1a3167cdcdb1.png">

**Comment by stevestreza** [comment] 2018-06-28 05:05
I have the same issue, I was able to temporarily work around it by deleting the deprecation warning listed in the `joblib/memory.py` file, which obviously isn't a permanent fix, but it got the project running.

**Comment by davidjohnbaker1** [comment] 2018-06-28 09:46
Hmm. There must be some other fix. I wouldn't be opposed to doing that, but fear I'd mess more things up in the process.

**Comment by drensin** [comment] 2018-07-02 01:07
hmmm...  I can reproduce this error (and I'm trying!)

-dave

**Comment by drensin** [comment] 2018-10-23 04:34
I've cleaned up the code to be Python3 compatible. I'm curious if that fixes your deprecation errors?

**Comment by dturner** [comment] 2018-10-23 11:28
I fixed this by running `pip install --user soundfile`

**Comment by drensin** [comment] 2018-10-24 05:37
That *shouldn't* be necessary because pygame should catch it, but.. it couldn't hurt!

**Comment by drensin** [comment] 2018-10-24 05:39
fixed in README. Thanks!

**Closed as completed by drensin** 2018-10-24 05:39 UTC
